function test(){
	var title = $("img.icon-ideas").data().value;
	var id = $('img.icon-ideas').attr("data-info");

	console.log('cliked li ' + id);
	$targetID = $(this).attr('data-info');
            console.log("Selected ID:" + $targetID);
}

$("#ideasGeradas li").on("click", ".icon-ideas", function() {

			console.log("Start click:");
            $targetID = $(this).attr('data-info');
            console.log("Selected ID:" + $targetID);

            // REMOVE WILL COME HERE
        });


router.post('/uploadfile', upload.single('myFile'), (req, res, next) => {
  const file = req.file
  if (!file) {
    const error = new Error('Please upload a file')
    error.httpStatusCode = 400
    return next(error)

  }


    res.send(file)
 
})


cloudinary.uploader.upload("sample.jpg", {"crop":"limit","tags":"samples","width":3000,"height":2000}, function(result) { console.log(result) });

cloudinary.image("sample", {"crop":"fill","gravity":"faces","width":300,"height":200,"format":"jpg"});

Cloud name:
hmsjccygb

API key:
271288152319538

API secret:
9lJbcPjXQOWJlxstpLgNw3XGIQA



cloudinary://271288152319538:9lJbcPjXQOWJlxstpLgNw3XGIQA@hmsjccygb/



var form = new formidable.IncomingForm();

    form.parse(req);

    form.on('fileBegin', function (name, file){
        file.path = __dirname + '/data/' + file.name;
        console.log('file path ' +file.path);
    });

    form.on('file', function (name, file){
        console.log('Uploaded ' + file.name);

var photo = new Photo(req.body);
  // Get temp file path
  var imageFile = file.name;
  // Upload file to Cloudinary
  cloudinary.uploader.upload(imageFile, { tags: 'express_sample' })
    .then(function (image) {
      console.log('** file uploaded to Cloudinary service');
      console.dir(image);
      photo.image = image;
      // Save photo with image metadata
      return photo.save();
    })
    .then(function () {
      console.log('** photo saved');
    })
    .finally(function () {
      res.render('photos/create_through_server', { photo: photo, upload: photo.image });
    });




         res.statusCode = 302;
                res.setHeader("Location", "http://sfc.fabricadecriatividade.com.br/prototipacao2.html");
                  res.end();
    });




function uploadImage() {
  cloudinary.uploader.upload('pizza.jpg', { tags: 'basic_sample' }, function (err, image) {
  console.log();
  console.log("** File Upload");
  if (err) { console.warn(err); }
  console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
  console.log("* " + image.public_id);
  console.log("* " + image.url);
});

}


app.post('/uploadfile', function(req, res) => {
 if(req.file) {
  //const file = dataUri(req).content;
  return uploader.upload('pizza.jpg').then((result) => {
    const image = result.url;
    return res.status(200).json({
      messge: 'Your image has been uploded successfully to cloudinary',
      data: {
        image
      }
    })
  }).catch((err) => res.status(400).json({
    messge: 'someting went wrong while processing your request',
    data: {
      err
    }
  }))
 }
});


Photo.create({
            clienteId: req.body.idCliente,
            imgURL: req.body.upload
        })




        form.parse(req, function (err, fields, files) {
      var oldpath = files.upload.path;
      var Nameimage = __dirname + files.upload.name;
      console.log('file url: ' +Nameimage)

      cloudinary.uploader.upload(Nameimage, { 
            tags: 'basic_sample' 

        },function(err) {
                  if (err) {
                      console.log(err);
                  } else {
                      res.statusCode = 302;
                      res.setHeader("Location", "http://sfc.fabricadecriatividade.com.br/prototipacao2.html");
                      res.end();
                      console.log('saved solucao');
                      
                  }
              });

        });


        
//Creating prototipacao 1
router.post("/prototipacao", function(req, res) {

    var photo = 'http://sfc.fabricadecriatividade.com.br/imagens-site/logo.png';

      var form = new formidable.IncomingForm();

          form.parse(req);

          form.on('fileBegin', function (name, file){
              file.path = __dirname + '/data/' + file.name;
              console.log('file path ' +file.path);
          });

          form.on('file', function (name, file){
              console.log('Uploaded ' + file.name);

      var photo = new Photo(req.body);
        // Get temp file path
        var imageFile = file.name;

        console.log('file name ariene : ' + imageFile )
        // Upload file to Cloudinary

            cloudinary.uploader.upload(imageFile, { 
                tags: 'basic_sample' 

            },function(err) {
                      if (err) {
                          console.log(err);
                      } else {
                          res.statusCode = 302;
                          res.setHeader("Location", "http://sfc.fabricadecriatividade.com.br/prototipacao2.html");
                          res.end();
                          console.log('saved solucao');
                          
                      }
                  });
    
      });

  });   

